# Generated by Django 3.2.21 on 2023-10-01 13:46

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Featured_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
            ],
        ),
        migrations.AlterModelOptions(
            name='booking_details',
            options={'ordering': ['-Date']},
        ),
        migrations.RenameField(
            model_name='booking_details',
            old_name='People',
            new_name='People_No',
        ),
        migrations.RemoveField(
            model_name='booking_details',
            name='Comment',
        ),
        migrations.RemoveField(
            model_name='booking_details',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='booking_details',
            name='Phone',
        ),
        migrations.AddField(
            model_name='booking_details',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=200)),
                ('Last_Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField()),
                ('Booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingsystem.booking_details')),
            ],
            options={
                'ordering': ['-First_Name'],
            },
        ),
    ]
