# Generated by Django 3.2.21 on 2023-10-12 12:33

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0002_auto_20231001_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_details',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='booking_details',
            name='Featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='booking_details',
            name='Phone_Number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='booking_details',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
