# Generated by Django 3.2.21 on 2023-10-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0003_auto_20231012_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='Meal_Name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
