# Generated by Django 3.2.21 on 2023-10-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0008_alter_booking_details_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_details',
            name='Slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
