# Generated by Django 3.2.21 on 2023-10-20 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0009_booking_details_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='Meal_des',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
