# Generated by Django 3.2.21 on 2023-10-22 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0010_menu_meal_des'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
