# Generated by Django 3.2.23 on 2023-12-07 15:43

import bookingsystem.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0012_alter_booking_details_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_details',
            name='Date',
            field=models.DateField(),
        ),
    ]
