# Generated by Django 3.2.23 on 2023-12-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0013_alter_booking_details_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_details',
            name='Phone_Number',
            field=models.CharField(max_length=15),
        ),
    ]
