# Generated by Django 3.2.23 on 2023-12-09 12:33

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0015_alter_booking_details_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_details',
            name='Phone_Number',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
