# Generated by Django 3.2.23 on 2023-12-09 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0019_auto_20231209_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_details',
            name='Featured_image',
        ),
        migrations.RemoveField(
            model_name='booking_details',
            name='body',
        ),
    ]
