# Generated by Django 3.2.23 on 2023-12-11 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0028_alter_booking_details_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_details',
            name='Phone_Number',
            field=models.TextField(error_messages={'required': 'Please enter number without signs'}, max_length=100, null=True, validators=[django.core.validators.RegexValidator('[+-/%]', inverse_match=True)]),
        ),
    ]
