# Generated by Django 3.2.23 on 2023-12-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0032_alter_booking_details_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_details',
            name='Phone_Number',
            field=models.TextField(blank=True, help_text='enter without + Contact phone number', null=True),
        ),
    ]
