# Generated by Django 3.2.23 on 2023-12-11 12:39

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0034_alter_booking_details_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_details',
            name='Phone_Number',
        ),
        migrations.AddField(
            model_name='booking_details',
            name='Phone_Number_0',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='IR', unique=True),
        ),
        migrations.AddField(
            model_name='booking_details',
            name='Phone_Number_1',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='IR', unique=True),
        ),
    ]
