# Generated by Django 3.2.23 on 2023-12-11 13:00

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0035_auto_20231211_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_details',
            name='Phone_Number_0',
        ),
        migrations.RemoveField(
            model_name='booking_details',
            name='Phone_Number_1',
        ),
        migrations.AddField(
            model_name='booking_details',
            name='Phone_Number',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
