# Generated by Django 3.2.23 on 2023-12-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0036_auto_20231211_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_details',
            name='Phone_Number',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
