# Generated by Django 3.2.23 on 2024-01-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0037_alter_booking_details_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_details',
            name='Slug',
            field=models.SlugField(null=True),
        ),
    ]
