# Generated by Django 3.2.23 on 2024-01-29 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookingsystem', '0038_alter_booking_details_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_details',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='booking_details',
            name='First_Name',
        ),
        migrations.RemoveField(
            model_name='booking_details',
            name='Last_Name',
        ),
        migrations.AddField(
            model_name='booking_details',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to=settings.AUTH_USER_MODEL),
        ),
    ]
