# Generated by Django 3.2.23 on 2024-01-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0039_auto_20240129_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_details',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='booking_details',
            name='First_Name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='booking_details',
            name='Last_Name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
