# Generated by Django 3.2.23 on 2024-04-05 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0040_auto_20240130_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_details',
            name='Slug',
        ),
    ]
