# Generated by Django 3.2.23 on 2024-04-05 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0041_remove_booking_details_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_details',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='booking_details',
            name='First_Name',
        ),
        migrations.RemoveField(
            model_name='booking_details',
            name='Last_Name',
        ),
    ]
