# Generated by Django 3.2.23 on 2024-04-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0042_auto_20240405_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_details',
            name='Phone_Number',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
